name: SecureExam CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: test_secret
      EMAIL_USER: test@example.com
      EMAIL_PASS: test_password

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build